services:  
  nginx:
    container_name: nginx
    image: nginx:1.27.0-alpine3.19-slim        
    ports:
      - 80:80        
    volumes:
      - ./nginx:/etc/nginx/conf.d      
    depends_on:     
      - attacker.demo.ru
      - page.demo.ru  
  
  attacker.demo.ru:
    container_name: attacker.demo.ru
    image: node:20-alpine3.19        
    working_dir: /opt/server
    volumes:
      - ./attacker:/opt/server           
    command: node server.js

  page.demo.ru:
    container_name: page.demo.ru        
    image: nginx:1.27.0-alpine3.19-slim         
    volumes:
      - ./page/nginx:/etc/nginx/conf.d
      - ./page/www:/var/www/page.demo.ru/html    
            
volumes:
  csp-volume:
    external: false
    
networks:
  csp-network:
    driver: bridge